#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/../install.conf

if [ `whoami` != "$WEBMO_USER" ]; then
	echo "You are `whoami`, but this script must be run as $WEBMO_USER"
	exit
fi

# name of the snapshot
name=$1

# path to sitc on snapshot
sitcpath=$2

mkdir $name

$DIR/gcloud/api start_snapshot $name $name
fullname=`$DIR/gcloud/api get_fullname $name`
scp $fullname:$sitcpath/engines.log $name/engines.log
