#!/bin/bash

name=$1
snapshotName=$2

gcloud compute disks create $name --size $DISKSIZE --source-snapshot $snapshotName

gcloud compute instances create $name --machine-type "n1-$MEMORY-$NUMCPUS" --disk "name=$name,device-name=$name,mode=rw,boot=yes,auto-delete=yes"

gcloud compute config-ssh
rm /home/$WEBMO_USER/.ssh/config
# Automatic passwordless ssh
cp /home/$WEBMO_USER/.ssh/google_compute_engine /home/$WEBMO_USER/.ssh/id_rsa
# Remove the host from knownhosts in case it collides with an existing one
ssh-keygen -f "/home/$WEBMO_USER/.ssh/knownhosts" -R $name
