#!/bin/bash

name=$1
snapshotName=$2

gcloud compute disks create $name --size $DISKSIZE --source-snapshot $snapshotName

gcloud compute instances create $name --machine-type "n1-$MEMORY-$NUMCPUS" --disk "name=$name,device-name=$name,mode=rw,boot=yes,auto-delete=yes"

gcloud compute config-ssh
rm /home/$WEBMO_USER/.ssh/config
# Passwordless ssh
cp /home/$WEBMO_USER/.ssh/google_compute_engine /home/$WEBMO_USER/.ssh/id_rsa
# Remove the host from knownhosts in case it collides with an existing one
ssh-keygen -R $name
# Remove the ip from knownhosts in case it collides with an existing one
ip=`gcloud compute instances list "$name" | tail -1 | rev | awk '{ print $3 }' | rev`
ssh-keygen -R $ip

# Get the correct host/ip added to knownhosts
echo "exit" | ssh -o StrictHostKeyChecking=no $name
