#!/bin/bash

#Obtain current directory
export SITC_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export SITC_LOG="$SITC_ROOT/sitc.log"
source $SITC_ROOT/install.conf
source $SITC_ROOT/util

for param in $@; do
	# Potentially override defaults in install.conf
	if [ "`echo $param | cut -c1-2`" == "--" ]; then
		paramname=`echo $param | cut -c3- | cut -d "=" -f1 | tr 'a-z-' 'A-Z_'`
		option=`echo $param | cut -c3- | cut -s -d "=" -f2`
		if [ -z "$option" ]; then
			option="true"
		fi
		if [ "$paramname" == "HELP" ]; then
			printHelp
			quit
		fi
		export "$paramname=$option"
	elif [ "`echo $param | cut -c1-1`" == "-" ]; then
		param="`echo $param | cut -c2-`" # remove the '-'
		case $param in
			"y") YES_TO_PROMPTS=true ;;
			"yy") YES_TO_PROMPTS=true; YES_TO_SANITY_CHECK=true ;;
			"v") cat $SITC_ROOT/version && exit ;;
			"h") printHelp && exit ;;
		esac
	fi
done

echo
echo "Server In The Cloud version `cat $SITC_ROOT/version`"
echo "Copyright (c) 2017, WebMO, LLC, all rights reserved."
echo

if [ "$YES_TO_PROMPTS" == "false" ]; then
	echo "This script automates the installation of software from several"
	echo "third parties. Many of these have licenses that are agreed to"
	echo "automatically by this script. Indicate your consent by pressing"
	echo "ENTER, or press CTRL-c to exit."
	echo
	read ans
fi

if [ "$YES_TO_SANITY_CHECK" != "true" ]; then
	echo "Sanity check! You have selected to do the following:"
	summarizeSettings
	echo "Press ENTER to continue, or CTRL-c to exit."
	echo
	read ans
fi

if [ -n "`uname -a | grep -i Debian`" ]; then
   OS="debian"
elif [ -n "`uname -a | grep -i ubuntu`" ]; then
   OS="ubuntu"
elif [ -e "/etc/redhat-release" ]; then
   OS="centos"
else
   echo "Unidentified OS! Exiting."
   exit
fi

echo "Installing for $OS"
echo
echo "Logging script output to $SITC_LOG"

if [ "$SKIP_UPDATE" != "true" ]; then
	echo
	echo "*** RUNNING OS_UPDATE ***"
	$SITC_ROOT/scripts/$OS/os_update
fi

if [ "$SKIP_WEBMO" != "true" ]; then
	echo
	echo "*** RUNNING INSTALL_WEBMO ***"
	$SITC_ROOT/scripts/$OS/install_webmo $SITC_ROOT
fi

echo
echo "*** INSTALLING ENGINES ***"
for engine in `sed 's/,/ /g' <<< $ENGINES`; do
        echo "Installing $engine"
	if [ -e "$SITC_ROOT/scripts/$OS/install_$engine" ]; then
		# Distro specific installation instructions
	        $SITC_ROOT/scripts/$OS/install_$engine
	fi
	# Common insallation instructions
	$SITC_ROOT/scripts/common/install_$engine
	echo
done

if [ "$SKIP_WEBMO" != "true" ]; then
	echo
	echo "Enabling engines in WebMO"
	sudo $SITC_ROOT/scripts/common/enable_in_webmo $SITC_ROOT/engines.log /home/$WEBMO_USER/public_html/cgi-bin/webmo/interfaces

	IP=`curl -s "http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip" -H "X-Google-Metadata-Request: True"`
	echo "

*** CONFIGURE INSTALLATION ***

In your web browser, log in to $IP/$WEBMO_USER with the
username \"admin\" and a blank password. Set the admin password.

Run a test job."
fi
echo
