#!/bin/bash

#Obtain current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/install.conf

accept_all=false

printHelp()
{
echo "Usage: install [OPTIONS...]
Installs WebMO and (a) computational chemistry engine(s).

WebMO options:
  --WEBMO_USER=<name>	unix user WebMO software will be installed under
  --WEBMO_LICENSE=<license>
			license used to download and instal WebMO
  --WEBMO_PASSWORD=<password>
			password that corresponds to WEBMO_LICENSE
  --WEBMO_INITIAL_USERS=<users>
			quoted space separated username:password
  --SKIP_WEBMO=<true/false>
			optionally omit webmo (install engines only)

Engine options:
  --ENGINE_DIR=<path>	path to directory that engines are to be installed in
  --ENGINES=<engines>	quoted space separated engines

Available engines:"
for file in `ls $DIR/scripts/common`; do
	if [ "`echo $file | cut -c1-7`" == "install" ]; then
		engine="`echo $file | cut -c9-`"
		if [ "$engine" != "webmo" ]; then
			echo "  $engine"
		fi
	fi
done

echo
echo "Miscellaneous:
  -y			accept licenses and don't prompt for continuing
  -v			display version information and exit
  -h			display this help text and exit"
exit
}

for param in $@; do
	# Potentially override defaults in install.conf
	if [ "`echo $param | cut -c1-2`" == "--" ]; then
		export "`echo $param | cut -c3-`"
	elif [ "`echo $param | cut -c1-1`" == "-" ]; then
		param="`echo $param | cut -c2-`" # remove the '-'
		for var in `echo "$param" | sed -e 's/\(.\)/\1\n/g'`; do
			case $var in
				"y") accept_all=true ;;
				"v") cat $DIR/version && exit ;;
				"h") printHelp ;;
			esac
		done
	fi
done

#if [ "$accept_all" == "true" ] && [ -z "$WEBMO_LICENSE" -o -z "$WEBMO_PASSWORD" ]; then
#	echo "ERROR: Cannot be accept_all without specifying both WEBMO_LICENSE and WEBMO_PASSWORD"
#	exit
#fi

#if [ -n "`echo $ENGINES | grep "mopac7"`" ] && [ -n "`echo $ENGINES | grep "openmopac"`" ]; then
#	echo "ERROR: Cannot install both mopac7 and openmopac"
#	exit
#fi

echo "Server In The Cloud version `cat $DIR/version`"
echo "Copyright (c) 2016, WebMO, LLC, all rights reserved."

if [ ! -e $DIR/license_agreed ] && [ "$accept_all" == "false" ]; then
	echo
	echo "This script automates the installation of software from several"
	echo "third parties. Many of these have licenses that are agreed to"
	echo "automatically by this script. Indicate your consent by pressing"
	echo "ENTER, or press CTRL-c to exit."
	echo
	read ans
	touch $DIR/license_agreed
fi

if [ -n "`uname -a | grep -i Debian`" ]; then
   OS="debian"
elif [ -n "`uname -a | grep -i ubuntu`" ]; then
   OS="ubuntu"
elif [ -e "/etc/redhat-release" ]; then
   OS="centos"
else
   echo "Unidentified OS! Exiting."
   exit
fi

echo -e "Installing for $OS"

echo "*** RUNNING OS_ADDITIONS ***"
$DIR/scripts/$OS/os_additions $DIR
if [ "$accept_all" == "false" ]; then
	read -s -n 1 -p "Press any key to continue"
fi

if [ "$SKIP_WEBMO" != "true" ]; then
	echo -e "\n"
	echo "*** RUNNING INSTALL_WEBMO ***"
	$DIR/scripts/$OS/install_webmo $DIR $accept_all
	if [ "$accept_all" == "false" ]; then
		read -s -n 1 -p "Press any key to continue"
	fi
fi

echo -e "\n"
echo "*** INSTALLING ENGINES ***"
for engine in $ENGINES; do
        echo -e "Installing $engine"
        $DIR/scripts/$OS/install_$engine $DIR
done
if [ "$accept_all" == "false" ]; then
        read -s -n 1 -p "Press any key to continue"
fi

echo -e "\n"
echo "*** COPYING SCRIPTS TO /HOME/WEBMO ***"
sudo cp -a $DIR/../sitc /home/webmo/
sudo chown -R webmo:webmo /home/webmo/sitc
if [ "$accept_all" == "false" ]; then
        read -s -n 1 -p "Press any key to continue"
fi

IP=`curl -s "http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip" -H "X-Google-Metadata-Request: True"`

echo "

*** CONFIGURE INSTALLATION ***

In your web browser, login to $IP/$WEBMO_USER with the
username \"admin\" and a blank password. Set the admin password.

Run a test job.
"
