#!/bin/bash

printDefault() {
var=$1
if [ ! -z "$var" ]; then
        echo "
                       default: $var"
fi
}

printHelp()
{
echo "Usage: install [OPTIONS...]
Installs WebMO and (a) computational chemistry engine(s).

WebMO options:
  --webmo-user=<name>  unix user WebMO software will be installed under`printDefault $WEBMO_USER`
  --webmo-license=<license>
                       license used to download and install WebMO`printDefault $WEBMO_LICENSE`
  --webmo-password=<password>
                       password that corresponds to WEBMO_LICENSE`printDefault $WEBMO_PASSWORD`
  --webmo-initial-users=<users>
                       comma separated username:password`printDefault $WEBMO_INITIAL_USERS`
  --skip-webmo         omit webmo (install engines only)`printDefault $SKIP_WEBMO`

Engine options:
  --engine-dir=<path>  path to directory that engines are to be installed in`printDefault $ENGINE_DIR`
  --engines=<engines>  comma separated engines to be installed on this computer`printDefault $ENGINES`

Available engines:"
for file in `ls $SITC_ROOT/scripts/common`; do
	if [ "`echo $file | cut -c1-7`" == "install" ]; then
		engine="`echo $file | cut -c9-`"
		if [ "$engine" != "webmo" ]; then
			echo "  $engine"
		fi
	fi
done

for file in `ls $SITC_ROOT/scripts/common`; do
        if [ "`echo $file | cut -c1-7`" == "install" ]; then
                engine="`echo $file | cut -c9-`"
                if [ "$engine" != "webmo" ]; then
                        $SITC_ROOT/scripts/common/install_$engine "true"
                fi
        fi
done

echo
echo "Miscellaneous:
  --skip-update        skips performing a system update
  -y, --yes-to-prompts
                       accept licenses and don't prompt for continuing
  --yes-to-sanity-check
                       bypass sanity check
  -yy                  same as --yes-to-prompts and --yes-to-sanity-check
  -v                   display version information and exit
  -h, --help           display this help text and exit"
exit
}

summarizeSettings() {
	if [ "$SKIP_UPDATE" != "true" ]; then
		echo " Update the operating system"
	fi
	if [ "$SKIP_WEBMO" == "true" ]; then
		echo " Skip installing WebMO"
	else
		echo " Install WebMO for user $WEBMO_USER"
	fi
	if [ -n "$ENGINES" ]; then
                echo " Install $ENGINES to $ENGINE_DIR"
        fi
}

