#!/bin/bash

printDefault() {
var=$1
if [ ! -z "$var" ]; then
        echo "
                       default: $var"
fi
}

printHelp()
{
echo "Usage: install [OPTIONS...]
Installs WebMO and (a) computational chemistry engine(s).

WebMO options:
  --WEBMO_USER=<name>  unix user WebMO software will be installed under`printDefault $WEBMO_USER`
  --WEBMO_LICENSE=<license>
                       license used to download and install WebMO`printDefault $WEBMO_LICENSE`
  --WEBMO_PASSWORD=<password>
                       password that corresponds to WEBMO_LICENSE`printDefault $WEBMO_PASSWORD`
  --WEBMO_INITIAL_USERS=<users>
                       comma separated username:password`printDefault $WEBMO_INITIAL_USERS`
  --SKIP_WEBMO=<true/false>
                       omit webmo (install engines only)`printDefault $SKIP_WEBMO`

Engine options:
  --ENGINE_DIR=<path>  path to directory that engines are to be installed in`printDefault $ENGINE_DIR`
  --ENGINES=<engines>  comma separated engines to be installed on this computer`printDefault $ENGINES`

Available engines:"
for file in `ls $SITC_ROOT/scripts/common`; do
	if [ "`echo $file | cut -c1-7`" == "install" ]; then
		engine="`echo $file | cut -c9-`"
		if [ "$engine" != "webmo" ]; then
			echo "  $engine"
		fi
	fi
done

for file in `ls $SITC_ROOT/scripts/common`; do
        if [ "`echo $file | cut -c1-7`" == "install" ]; then
                engine="`echo $file | cut -c9-`"
                if [ "$engine" != "webmo" ]; then
                        $SITC_ROOT/scripts/common/install_$engine "true"
                fi
        fi
done

echo
echo "Miscellaneous:
  --YES_TO_ALL=<true/false>
                       accept licenses and don't prompt for continuing
  -y                   same as --YES_TO_ALL=true
  -v                   display version information and exit
  -h                   display this help text and exit"
exit
}

summarizeSettings() {
	if [ -n "$ENGINES" ]; then
		echo "Installing $ENGINES to $ENGINE_DIR"
	fi
	if [ "$SKIP_WEBMO" == "true" ]; then
		echo "WebMO will not be installed"
	else
		echo "WebMO will be installed for user $WEBMO_USER"
	fi
}

