#!/bin/bash

username=$1
password=$2

cd /home/$WEBMO_USER/public_html/cgi-bin/webmo

sudo su $WEBMO_USER -c "perl -e \"
	use lib '/home/$WEBMO_USER/public_html/cgi-bin/webmo';
	require qw(usercontrol.cgi);
	create_user(\"$username\", 'webmo', \"$password\", '0');
        \""
sudo su $WEBMO_USER -c "perl -e \"
	use lib '/home/$WEBMO_USER/public_html/cgi-bin/webmo';
	require qw(usercontrol.cgi);
        my %user_profile;
        \\\$user_profile{'timeLimit'} = -1;
     	\\\$user_profile{'jobTimeLimit'} = 'group';
      	\\\$user_profile{'enabledInterfaces'} = 'group';
      	\\\$user_profile{'enabledServers'} = 'group';
    	\\\$user_profile{'enabledQueues'} = 'group';
  	&set_user_profile(\"$username\", \\%user_profile);
        \""
