#!/bin/bash

# Since this script gets run on systems without passwordless sudo, it
# should be called as sudo in situations where permissions are needed.

# File containing engines
log=$1

# Directory containing engine.int.(disabled)
path=$2

for engine in `grep -Po "<[^/]*>" $log | tr -d "<>"`; do
	mv $path/$engine.int.disabled $path/$engine.int
	for setting in `grep -Pzo "<$engine>[^<>]*</$engine>" $log | sed "s&</\?$engine>&&"`; do
		name=`echo $setting | cut -d "=" -f1`
		sed -i "s&$name=.*&$setting&" $path/$engine.int
	done
done

if [ -n "`echo $path | grep -o 'cgi-bin/webmo/servers'`" ]; then
	# This is a remote server, so copy all engine.int files over
	dest=`grep '^cgiBase=' $path/globals.int | cut -d "=" -f2 | sed 's/\"//g'`
	host=`grep '^host=' $path/globals.int | cut -d "=" -f2 | sed 's/\"//g'`
	cd $path
	for file in `ls *.int`; do
		if [ "$file" != "globals.int" ]; then
			scp $path/$file $host:$dest/interfaces/$file
		fi
	done
fi
