#!/bin/bash

# Since this script gets run on systems without passwordless sudo, it
# should be called as sudo in situations where permissions are needed.

# File containing engines
log=$1

# Directory containing engine.int.(disabled)
path=$2

for engine in `grep -Po "<[^/]*>" $log | tr -d "<>"`; do
	mv $path/$engine.int.disabled $path/$engine.int &> /dev/null
	echo "Enabling $engine"
	for setting in `grep -Pzo "<$engine>[^<>]*</$engine>" $log | sed "/<\/\?$engine>/d"`; do
		name=`echo $setting | cut -d "=" -f1`
		echo "Setting $setting"
		sed -i "s&$name=.*&$setting&" $path/$engine.int
	done
	echo
done
