#!/bin/bash

help_and_exit=$1

if [ "$help_and_exit" == "true" ]; then
        echo "
Gaussian:
  --GAUSSIAN_TAR=<path>
                       location of the gaussian tar file"
        exit
fi

cd /etc
sudo cp -p group group.bak
sudo cp -p gshadow gshadow.bak
sudo groupadd -g 499 gaussian
sudo usermod -a -G gaussian $WEBMO_USER

cd $ENGINE_DIR
while [ ! -e "$GAUSSIAN_TAR" ]; do
        echo -n "Enter the location of the gaussian tar: "
        read GAUSSIAN_TAR
done
echo "Unpacking gaussian..."
sudo tar xzf $GAUSSIAN_TAR
sudo chown -R root:gaussian g09

echo "Enabling gaussian in WebMO..."
cd /home/$WEBMO_USER/public_html/cgi-bin/webmo/interfaces/ >> $SITC_ROOT/sitc.log 2>&1
sudo mv gaussian.int.disabled gaussian.int >> $SITC_ROOT/sitc.log 2>&1
sudo sed -i "s&/usr/local&$ENGINE_DIR&g" gaussian.int >> $SITC_ROOT/sitc.log 2>&1
