#!/bin/bash

help_and_exit=$1

if [ "$help_and_exit" == "true" ]; then
        exit
fi

# Download and untar mopac7 to /usr/local
echo "Downloading mopac7..."
cd $ENGINE_DIR
sudo curl -s -O http://webmo.net/cloud/software/mopac7-bin.tar.gz
echo "Untarring mopac7 to $ENGINE_DIR..."
sudo tar xzf mopac7-bin.tar.gz
sudo chown -R root:root mopac7

if [ ! "$SKIP_WEBMO" == "true" ]; then
        echo "Enabling mopac7 in WebMO..."
        $SITC_ROOT/scripts/common/enable_in_webmo mopac7 /home/$WEBMO_USER/public_html/cgi-bin/webmo/interfaces/
fi
