#!/bin/bash

help_and_exit=$1

if [ "$help_and_exit" == "true" ]; then
	source $SITC_ROOT/util
        exit
fi

# Download and untar mopac7 to /usr/local
echo "Downloading mopac7..."
cd $ENGINE_DIR
sudo curl -s -O https://webmo.net/cloud/software/mopac7-bin.tar.gz
echo "Untarring mopac7 to $ENGINE_DIR..."
sudo tar xzf mopac7-bin.tar.gz
sudo chown -R root:root mopac7

echo "Logging installation options..."
$SITC_ROOT/scripts/common/log_engine mopac7
