#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd /usr/local

echo "Unpacking gamess"
sudo tar xzf gamess-current.tar.gz
sudo chown -R root:root gamess

echo "Configuring installation"
cd gamess
GFORTVERS=`gfortran -dumpversion | cut -c1-3`

# Gamess doesn't normally compile for gfortran version > 4.9, but that's only because of
# checks in the config and comp files, not because of incompatabilities in the code.
if (( $(echo "$GFORTVERS 4.9" | awk '{print ($1 > $2)}') )); then
	sed "s/X/$GFORTVERS/" $DIR/../../patches/gamess_config.patch | sudo patch config
	sed "s/X/$GFORTVERS/" $DIR/../../patches/gamess_comp.patch | sudo patch comp
fi

echo "
linux64



gfortran
$GFORTVERS

none


sockets
no
" | sudo ./config

echo "Compiling ddi"
cd ddi
sudo ./compddi
sudo mv ddikick.x ..
cd ..

echo "Compiling gamess"
sudo ./compall
sudo ./lked gamess 00

sudo patch rungms < $DIR/../../patches/rungms.patch
