#!/bin/bash

help_and_exit=$1

if [ "$help_and_exit" == "true" ]; then
        exit
fi

# Download and untar mopac7 to /usr/local
echo "Downloading mopac7..."
cd $ENGINE_DIR
sudo curl -s -O http://webmo.net/cloud/software/mopac7-bin.tar.gz
echo "Untarring mopac7 to $ENGINE_DIR..."
sudo tar xzf mopac7-bin.tar.gz
sudo chown -R root:root mopac7

echo "Enabling mopac7 in WebMO..."
# Enable mopac7 in WebMO
cd /home/$WEBMO_USER/public_html/cgi-bin/webmo/interfaces/ >> $SITC_ROOT/sitc.log 2>&1
sudo mv mopac.int.disabled mopac.int >> $SITC_ROOT/sitc.log 2>&1
sudo sed -i "s&mopacVersion=.*&mopacVersion=\"7\"&" mopac.int >> $SITC_ROOT/sitc.log 2>&1
sudo sed -i "s&mopacPath=.*&mopacPath=\"$ENGINE_DIR/mopac7/mopac.exe\"&" mopac.int >> $SITC_ROOT/sitc.log 2>&1
sudo sed -i "s&mopacExternal=.*&mopacExternal=\"\"&" mopac.int >> $SITC_ROOT/sitc.log 2>&1
