#!/bin/bash

help_and_exit=$1

if [ "$help_and_exit" == "true" ]; then
	echo "
Openmopac:
  --OPENMOPAC_LICENSE=<key>
                        license key for openmopac"
        exit
fi

cd $ENGINE_DIR
echo "Downloading openmopac..."
sudo curl -O http://openmopac.net/MOPAC2016_for_Linux_64_bit.zip >> $SITC_ROOT/sitc.log 2>&1
echo "Unzipping openmopac..."
sudo unzip -d mopac2016/ MOPAC2016_for_Linux_64_bit.zip >> $SITC_ROOT/sitc.log 2>&1
cd mopac2016/
sudo mv libiomp5.so /usr/lib/
sudo ldconfig
sudo chmod 755 MOPAC2016.exe
sudo chmod 777 .
export MOPAC_LICENSE=$ENGINE_DIR/mopac2016

if [ -z "$OPENMOPAC_LICENSE" ]; then
	echo "You should have received a password from Mr MOPAC."
	echo "If not, please go to http://openmopac.net/form.php and request one."
	echo -n "Enter the password you recieved from Mr MOPAC: "
	read OPENMOPAC_LICENSE
fi
echo -e "\nYes\n" | ./MOPAC2016.exe $OPENMOPAC_LICENSE >> $SITC_ROOT/sitc.log 2>&1
sudo chmod 755 .

echo "Enabling openmopac in WebMO..."
cd /home/$WEBMO_USER/public_html/cgi-bin/webmo/interfaces/
sudo mv mopac.int.disabled mopac.int > /dev/null 2>&1
sudo sed -i "s&mopacVersion=.*&mopacVersion=\"2016\"&" mopac.int
sudo sed -i "s&mopacPath=.*&mopacPath=\"$ENGINE_DIR/mopac2016/MOPAC2016.exe\"&" mopac.int
sudo sed -i "s&mopacExternal=.*&mopacExternal=\"\"&" mopac.int
