#!/bin/bash

help_and_exit=$1

if [ "$help_and_exit" == "true" ]; then
	echo "
Gamess:
  --GAMESS_TAR=<path>  location of the gamess tar file"
	exit
fi

cd $ENGINE_DIR

echo "Unpacking gamess"
while [ ! -e $GAMESS_TAR ]; do
	echo -n "Enter the location of the gamess tar: "
	read GAMESS_TAR
done
sudo tar xzf $GAMESS_TAR
sudo chown -R root:root gamess

echo "Configuring installation"
cd gamess
GFORTVERS=`gfortran -dumpversion | cut -c1-3`
if [ `echo "$GFORTVERS" | head -1` == "GNU" ]; then
	#Earlier versions of gfortran didn't dump the version nicely.
	GFORTVERS=`gfortran -dumpversion | head -1 | awk '{print $4}' | cut -c1-3`
fi

# Gamess doesn't normally compile for gfortran version > 4.9, but that's only because of
# checks in the config and comp files, not because of incompatabilities in the code.
if (( $(echo "$GFORTVERS 4.9" | awk '{print ($1 > $2)}') )); then
	sed "s/X/$GFORTVERS/" $SITC_ROOT/patches/gamess_config.patch | sudo patch config
	sed "s/X/$GFORTVERS/" $SITC_ROOT/patches/gamess_comp.patch | sudo patch comp
fi

echo "
linux64



gfortran
$GFORTVERS

none


sockets
no
" | sudo ./config

echo "Compiling ddi"
cd ddi
sudo ./compddi
sudo mv ddikick.x ..
cd ..

echo "Compiling gamess"
sudo ./compall
sudo ./lked gamess 00

sudo patch rungms < $SITC_ROOT/patches/rungms.patch

if [ ! "$SKIP_WEBMO" == "true" ]; then
	echo "Enabling gamess in WebMO..."
	$SITC_ROOT/scripts/common/enable_in_webmo gamess /home/$WEBMO_USER/public_html/cgi-bin/webmo/interfaces/
fi
