#!/bin/bash

#Obtain current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd /opt/
sudo curl -O http://openmopac.net/MOPAC2016_for_Linux_64_bit.zip
sudo unzip MOPAC2016_for_Linux_64_bit.zip -d mopac
cd mopac
sudo mv libiomp5.so /usr/lib/
sudo chmod 777 /opt/mopac/
sudo ldconfig
echo "You should have received a password from Mr Mopac."
echo "If not, please go to http://openmopac.net/form.php and request one."
echo -n "Enter the password you recieved from Mr MOPAC: "
read password
echo -e "\nYes\n" | ./MOPAC2016.exe $password
