#!/bin/bash

help_and_exit=$1

if [ "$help_and_exit" == "true" ]; then
        exit
fi

cd $ENGINE_DIR
# Install miniconda, psi4's installer
echo "Downloading miniconda..."
sudo curl -o Miniconda-latest.sh "https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh" -k >> $SITC_ROOT/sitc.log 2>&1
echo "Installing miniconda..."
sudo bash Miniconda-latest.sh -b -p $ENGINE_DIR/miniconda >> $SITC_ROOT/sitc.log 2>&1
export PATH=$ENGINE_DIR/miniconda/bin:$PATH
sudo env "PATH=$PATH" conda update --yes --all >> $SITC_ROOT/sitc.log 2>&1
sudo env "PATH=$PATH" conda config --add channels http://conda.anaconda.org/psi4 >> $SITC_ROOT/sitc.log 2>&1
echo "Installing psi4..."
sudo env "PATH=$PATH" conda install --yes psi4 >> $SITC_ROOT/sitc.log 2>&1

echo "Enabling psi4 in WebMO..."
# Enable psi4 in WebMO
cd /home/$WEBMO_USER/public_html/cgi-bin/webmo/interfaces/ >> $SITC_ROOT/sitc.log 2>&1
sudo mv psi.int.disabled psi.int >> $SITC_ROOT/sitc.log 2>&1
sudo sed -i "s&psiBase=.*&psiBase=\"$ENGINE_DIR/miniconda\"&" psi.int >> $SITC_ROOT/sitc.log 2>&1
