#!/bin/bash

help_and_exit=$1

if [ "$help_and_exit" == "true" ]; then
	source $SITC_ROOT/util
	echo "
Orca:
  --orca-tar=<path>    location of the file orca_X_X_X_linux_x86-64.tbz`printDefault $ORCA_TAR`"
        exit
fi

echo "Untarring orca to $ENGINE_DIR..."
cd $ENGINE_DIR

while [ ! -e $ORCA_TAR ]; do
        echo -n "Enter the location of the orca tar: "
        read ORCA_TAR
done

sudo tar xjf $ORCA_TAR
dirname=`ls /usr/local/ | grep "orca"`
sudo mv $dirname orca/
sudo chown -R root:root orca/

export ORCA_VERSION=`echo $dirname | grep -oP '\d_\d_\d' | tr '_' '.'`
export ORCA_PATH="$ENGINE_DIR/orca"

echo "Logging installation options..."
$SITC_ROOT/scripts/common/log_engine orca
