#!/bin/bash

help_and_exit=$1

if [ "$help_and_exit" == "true" ]; then
	source $SITC_ROOT/util
	echo "
Tinker:
  --tinker-version=<version>
                       version of Tinker to download and install`printDefault $TINKER_VERSION`"
        exit
fi

echo "Downloading tinker-$TINKER_VERSION.tar.gz to $ENGINE_DIR..."
cd $ENGINE_DIR
sudo curl -O https://dasher.wustl.edu/tinker/downloads/tinker-$TINKER_VERSION.tar.gz

echo "Untarring tinker-$TINKER_VERSION.tar.gz..."
sudo tar xzf tinker-$TINKER_VERSION.tar.gz
sudo chown -R root:root tinker/

sudo cp tinker/make/Makefile tinker/source/
cd tinker/source/
sudo patch Makefile < $SITC_ROOT/patches/tinker_makefile.patch

sudo make all
sudo mkdir ../bin/
sudo cp *.x ../bin/

echo "Logging installation options..."
$SITC_ROOT/scripts/common/log_engine tinker
