#!/bin/bash

license=$WEBMO_LICENSE
password=$WEBMO_PASSWORD

echo "Setting up WebMO user..."
# Set up WebMO user
sudo useradd -m $WEBMO_USER -s /bin/bash >> $SITC_ROOT/sitc.log 2>&1

echo "Creating public_html directory..."
# Create public_html directory
sudo mkdir /home/$WEBMO_USER/public_html
sudo mkdir /home/$WEBMO_USER/public_html/cgi-bin
sudo chown -R $WEBMO_USER:$WEBMO_USER /home/$WEBMO_USER/public_html
sudo chmod 711 /home/$WEBMO_USER
sudo chmod -R 755 /home/$WEBMO_USER/public_html/cgi-bin

echo "Installing WebMO..."
# Install WebMO
cd /tmp
while : ; do
	##### GET USERNAME AND PASSWORD #####
	credentials=`$SITC_ROOT/scripts/common/get_license.pl "$license" "$password"`
	# get_lecense.pl is set up to populate credentials with
	# your license and password.
	license=`echo $credentials | awk '{ print $1 }'`
	password=`echo $credentials | awk '{ print $2 }'`
	##### END GET USERNAME AND PASSWORD #####
	echo "Downloading WebMO..."
	# Download WebMO
	curl -o WebMO.tar.gz -s "http://www.webmo.net/nathan/WebMO.17.0.002e.tar.gz"
	#curl -o WebMO.tar.gz -s "http://www.webmo.net/cgi-bin/download/download.cgi?license=$license&password=$password&version=latest&operation=download"
	
	if [ "`cat WebMO.tar.gz`" != "Password not valid" ] && [ "`cat WebMO.tar.gz`" != "License not found" ]; then
		break;
	fi
	echo "Invalid license or password, try again."
	license=""
	password=""
done

echo "Unpacking WebMO..."
# Unpack WebMO
tar xzf WebMO.tar.gz

#Setup autoinstall script
sudo cat > /tmp/WebMO.install/setup.conf << EOF
license="$license"
perlPath="/usr/bin/perl"
webserver="localhost"
htmlBase="/home/$WEBMO_USER/public_html/webmo"
url_htmlBase="/~$WEBMO_USER/webmo"
cgiBase="/home/$WEBMO_USER/public_html/cgi-bin/webmo"
url_cgiBase="/~$WEBMO_USER/cgi-bin/webmo"
userBase="/home/$WEBMO_USER/webmo"
EOF

sudo chown -R $WEBMO_USER:$WEBMO_USER WebMO.install
cd WebMO.install
sudo su $WEBMO_USER -c "perl setup.pl" >> $SITC_ROOT/sitc.log 2>&1

echo "Cleaning up temporary files..."
cd ..
sudo rm -rf WebMO.install

# Make sure permissions are correct for /home/$WEBMO_USER/webmo
# (it can get messed up on different distributions)
sudo chmod 757 /home/$WEBMO_USER/webmo

if [ -n "$WEBMO_INITIAL_USERS" ]; then
	for user in `sed 's/,/ /g' <<< $WEBMO_INITIAL_USERS`; do
		username=`echo $user | cut -f1 -d ":"`
		password=`echo $user | cut -f2 -d ":"`
		$SITC_ROOT/scripts/common/create_webmo_user "$username" "$password"
	done
	exit
fi

# Set up a user?
answer="a" # just anything other than "n", "y", and ""
while [ "$answer" != "n" ] && [ "$answer" != "y" ] && [ "$answer" != "" ]; do
	echo -n "Set up a WebMO user? [y/n]:"
	read answer
done
if [ "$answer" == "y" ] || [ "$answer" == "" ]; then
	while [ : ]; do
		echo -n "Enter a username: "
		read username
		if [ "$username" == "" ]; then
			echo
			echo "Cannot have a blank username, try again."
			continue
		fi
		equal=0
		while [ $equal -eq 0 ]; do
			echo -n "Enter a password: "
			read -s password1
			echo
			echo -n "Enter password again: "
			read -s password2
			if [ "$password1" == "$password2" ]; then
				equal=1
			else
				echo
				echo "Passwords do not match. Try again."
			fi
		done
		if [ "$password1" == "" ]; then
                        echo
                        echo "Cannot have a blank password, try again."
                        continue
                fi
		cd /home/$WEBMO_USER/public_html/cgi-bin/webmo
		$SITC_ROOT/scripts/common/create_webmo_user "$username" "$password2"
		echo
		break
	done
fi
