#!/bin/bash

license=$WEBMO_LICENSE
password=$WEBMO_PASSWORD

echo "Setting up WebMO user..."
# Set up WebMO user
sudo useradd -m $WEBMO_USER -s /bin/bash >> $SITC_LOG 2>&1

echo "Creating public_html directory..."
# Create public_html directory
sudo mkdir /home/$WEBMO_USER/public_html &> /dev/null
sudo mkdir /home/$WEBMO_USER/public_html/cgi-bin &> /dev/null
sudo chown -R $WEBMO_USER:$WEBMO_USER /home/$WEBMO_USER/public_html
sudo chmod 711 /home/$WEBMO_USER
sudo chmod -R 755 /home/$WEBMO_USER/public_html/cgi-bin

echo "Installing WebMO..."
# Install WebMO
cd /tmp
while : ; do
	##### GET USERNAME AND PASSWORD #####
	$SITC_ROOT/scripts/common/get_license.pl "$license" "$password" "$SITC_ROOT/scripts/common/creds.txt"
	# get_lecense.pl is set up to populate the file in the parameter
	# with your license and password.
	license=`cat $SITC_ROOT/scripts/common/creds.txt | awk '{ print $1 }'`
	password=`cat $SITC_ROOT/scripts/common/creds.txt | awk '{ print $2 }'`
	##### END GET USERNAME AND PASSWORD #####
	echo "Downloading WebMO..."
	# Download WebMO
	curl -o WebMO.tar.gz -s "https://www.webmo.net/cgi-bin/download/download.cgi?license=$license&password=$password&version=latest&operation=download"
	
	if [ "`du WebMO.tar.gz | awk '{print $1}'`" -gt "1000" ]; then #1000 is an arbitrary cutoff
		break;
	fi
	cat WebMO.tar.gz
	echo "Try again."
	license=""
	password=""
done

echo "Unpacking WebMO..."
# Unpack WebMO
tar xzf WebMO.tar.gz


#Setup autoinstall script
sudo cat > /tmp/WebMO.install/setup.conf << EOF
license="$license"
perlPath="/usr/bin/perl"
webserver="localhost"
htmlBase="/home/$WEBMO_USER/public_html/webmo"
url_htmlBase="/~$WEBMO_USER/webmo"
cgiBase="/home/$WEBMO_USER/public_html/cgi-bin/webmo"
url_cgiBase="/~$WEBMO_USER/cgi-bin/webmo"
userBase="/home/$WEBMO_USER/webmo"
EOF

sudo chown -R $WEBMO_USER:$WEBMO_USER WebMO.install
cd WebMO.install

if [ "$UPGRADE_WEBMO" == "true" ]; then
	echo "Upgrading WebMO..."
	sudo su $WEBMO_USER -c "echo $license | perl upgrade.pl /home/$WEBMO_USER/public_html/cgi-bin/webmo/interfaces/globals.int" >> $SITC_LOG 2>&1
else
	sudo su $WEBMO_USER -c "perl setup.pl" >> $SITC_LOG 2>&1
fi
echo "Cleaning up temporary files..."
cd ..
sudo rm -rf WebMO.install
if [ "$UPGRADE_WEBMO" == "true" ]; then
	exit
fi
# Make sure permissions are correct for /home/$WEBMO_USER/webmo
# (it can get messed up on different distributions)
sudo chmod 757 /home/$WEBMO_USER/webmo

if [ "$YES_TO_PROMPTS" == "true" ]; then
	# We're done here
	exit
fi

if [ -n "$WEBMO_INITIAL_USERS" ]; then
	for user in `sed 's/,/ /g' <<< $WEBMO_INITIAL_USERS`; do
		username=`echo $user | cut -f1 -d ":"`
		password=`echo $user | cut -f2 -d ":"`
		$SITC_ROOT/scripts/common/create_webmo_user "$username" "$password"
	done
	exit
fi

# Set up a user?
answer="a" # just anything other than "n", "y", and ""
while [ "$answer" != "n" ] && [ "$answer" != "y" ] && [ "$answer" != "" ]; do
	echo -n "Set up a WebMO user? [y/n]:"
	read answer
done
if [ "$answer" == "y" ] || [ "$answer" == "" ]; then
	while [ : ]; do
		echo -n "Enter a username: "
		read username
		if [ "$username" == "" ]; then
			echo
			echo "Cannot have a blank username, try again."
			continue
		fi
		equal=0
		while [ $equal -eq 0 ]; do
			echo -n "Enter a password: "
			read -s password1
			echo
			echo -n "Enter password again: "
			read -s password2
			if [ "$password1" == "$password2" ]; then
				equal=1
			else
				echo
				echo "Passwords do not match. Try again."
			fi
		done
		if [ "$password1" == "" ]; then
                        echo
                        echo "Cannot have a blank password, try again."
                        continue
                fi
		cd /home/$WEBMO_USER/public_html/cgi-bin/webmo
		$SITC_ROOT/scripts/common/create_webmo_user "$username" "$password2"
		echo
		break
	done
fi
