#!/bin/bash

help_and_exit=$1

if [ "$help_and_exit" == "true" ]; then
	# Do nothing
	exit
fi

# Installed from packages, logging is all that's left

echo "Logging installation options..."
$SITC_ROOT/scripts/common/log_engine nwchem
