#!/bin/bash

help_and_exit=$1

if [ "$help_and_exit" == "true" ]; then
	source $SITC_ROOT/util
        echo "
Gaussian:
  --GAUSSIAN_TAR=<path>
                       location of the gaussian tar file`printDefault $GAUSSIAN_TAR`"
        exit
fi

cd /etc
sudo cp -p group group.bak
sudo cp -p gshadow gshadow.bak
sudo groupadd -g 499 gaussian
sudo usermod -a -G gaussian $WEBMO_USER

cd $ENGINE_DIR
while [ ! -e "$GAUSSIAN_TAR" ]; do
        echo -n "Enter the location of the gaussian tar: "
        read GAUSSIAN_TAR
done
echo "Unpacking gaussian..."
sudo tar xzf $GAUSSIAN_TAR
sudo chown -R root:gaussian $ENGINE_DIR/g09

echo "Logging installation options"
$SITC_ROOT/scripts/common/log_engine gaussian
