#!/bin/bash

SITC_ROOT=$1

echo "Installing csh..."
# Install csh
sudo apt-get -y install csh >> $SITC_ROOT/sitc.log 2>&1

echo "Installing gfortran..."
# Install gfortran
sudo apt-get -y install gfortran >> $SITC_ROOT/sitc.log 2>&1

$SITC_ROOT/scripts/common/install_gamess $SITC_ROOT
