#!/bin/bash

#Obtain current directory
SITC_ROOT=$1

#update os
$SITC_ROOT/scripts/ubuntu/os_update $SITC_ROOT

echo "Installing apache..."
# Install apache
sudo apt-get -y install apache2 >> $SITC_ROOT/sitc.log 2>&1

echo "Installing apache suexec..."
# Install apache suexec
sudo apt-get -y install apache2-suexec-custom >> $SITC_ROOT/sitc.log 2>&1

echo "Installing perl..."
# Install perl
sudo apt-get -y install libcgi-pm-perl >> $SITC_ROOT/sitc.log 2>&1
