#!/bin/bash

version=`cat /etc/redhat-release | grep -o '[0-9]' | awk '{ print $1 }' | head -n 1`

echo "Installing httpd..."
# Install httpd
sudo yum -y install httpd >> $SITC_ROOT/sitc.log 2>&1
if (( "$version" == 6 )); then
	sudo chkconfig --add httpd >> $SITC_ROOT/sitc.log 2>&1
	sudo service httpd start >> $SITC_ROOT/sitc.log 2>&1
else
	sudo systemctl enable httpd >> $SITC_ROOT/sitc.log 2>&1
	sudo systemctl start httpd >> $SITC_ROOT/sitc.log 2>&1
fi

echo "Installing perl..."
# Install perl
sudo yum -y install perl >> $SITC_ROOT/sitc.log 2>&1
sudo yum -y install perl-CGI >> $SITC_ROOT/sitc.log 2>&1

echo "Configuring httpd..."
# Configure httpd
$SITC_ROOT/scripts/centos/configure

$SITC_ROOT/scripts/common/install_webmo
