#!/bin/bash

cd /usr/local
sudo curl -O http://www.nwchem-sw.org/images/Nwchem-6.6.revision27746-src.2015-10-20.tar.gz
sudo tar xzf Nwchem-6.6.revision27746-src.2015-10-20.tar.gz

export NWCHEM_TOP="/usr/local/nwchem-6.6"

sudo yum -y install python-devel gcc-gfortran openmpi-devel tcsh make

sudo tee $NWCHEM_TOP/make.sh > $SITC_ROOT/sitc.log << EOF
#!/bin/bash
export USE_MPI=y
export NWCHEM_TARGET=LINUX64
export USE_PYTHONCONFIG=y
export PYTHONVERSION=2.6
export PYTHONHOME=/usr
export USE_INTERNALBLAS=y
export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib/:$LD_LIBRARY_PATH
export PATH=/usr/lib64/openmpi/bin/:$PATH
export NWCHEM_TOP=$NWCHEM_TOP
cd $NWCHEM_TOP/src
make nwchem_config NWCHEM_MODULES="all python"
make
EOF

sudo chmod +x $NWCHEM_TOP/make.sh

$SITC_ROOT/scripts/common/install_nwchem
