#!/bin/bash

export MUNGEUSER=981
sudo groupadd -g $MUNGEUSER munge
sudo useradd  -m -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge -u $MUNGEUSER -g munge  -s /sbin/nologin munge
export SLURMUSER=982
sudo groupadd -g $SLURMUSER slurm
sudo useradd  -m -c "Slurm workload manager" -d /var/lib/slurm -u $SLURMUSER -g slurm  -s /bin/bash slurm

sudo yum -y install epel-release
sudo yum -y install munge munge-libs munge-devel

sudo chown -R munge:munge /etc/munge/ /var/log/munge/
sudo chmod 0700 /etc/munge/ /var/log/munge/

sudo yum -y install nfs-utils
headname=`hostname | sed 's/[0-9]*$//'`
fstab="
$headname:/etc/slurm		/etc/slurm		nfs	ro,hard,intr	0 0
$headname:/home/webmo/.ssh	/home/webmo/.ssh	nfs	ro,hard,intr	0 0"
echo "$fstab" | sudo tee --append /etc/fstab > /dev/null
sudo mount /etc/munge
sudo mkdir /etc/slurm
sudo mount /etc/slurm

sudo systemctl enable munge
sudo systemctl start munge

cd /etc/slurm/
sudo yum -y install slurm-$VER*rpm slurm-devel-$VER*rpm slurm-munge-$VER*rpm slurm-perlapi-$VER*rpm slurm-plugins-$VER*rpm slurm-sjobexit-$VER*rpm slurm-sjstat-$VER*rpm slurm-torque-$VER*rpm slurm-seff-$VER*rpm

sudo mkdir /var/spool/slurmctld /var/log/slurm
sudo chown slurm: /var/spool/slurmctld /var/log/slurm
sudo chmod 755 /var/spool/slurmctld /var/log/slurm

sudo touch /var/log/slurm/slurmctld.log
sudo chown slurm: /var/log/slurm/slurmctld.log

sudo touch /var/log/slurm/slurm_jobacct.log /var/log/slurm/slurm_jobcomp.log
sudo chown slurm: /var/log/slurm/slurm_jobacct.log /var/log/slurm/slurm_jobcomp.log

#Make a good default slurm.conf
namescheme=`hostname`
slurmconf="ControlMachine=$namescheme
ReturnToService=2
SlurmUser=slurm
StateSaveLocation=/var/spool/slurmctld
ClusterName=cluster
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
NodeName=$namescheme[01-99] CPUs=1 State=UNKNOWN
PartationName=DEFAULT Nodes=$namescheme[01-99] Default=YES MaxTime=INFINITE State=UP"
echo "$slurmconf" | sudo tee /etc/slurm/slurm.conf > /dev/null
sudo systemctl enable slurmd
sudo systemctl start slurmd
