#!/bin/bash

version=`cat /etc/redhat-release | grep -o '[0-9]' | awk '{ print $1 }' | head -n 1`

echo "Installing httpd..."
# Install httpd
sudo yum -y install httpd >> $SITC_LOG 2>&1
if (( "$version" == 6 )); then
	sudo chkconfig --add httpd >> $SITC_LOG 2>&1
	sudo service httpd start >> $SITC_LOG 2>&1
else
	sudo systemctl enable httpd >> $SITC_LOG 2>&1
	sudo systemctl start httpd >> $SITC_LOG 2>&1
fi

echo "Installing perl..."
# Install perl
sudo yum -y install perl >> $SITC_LOG 2>&1
sudo yum -y install perl-CGI >> $SITC_LOG 2>&1

# The configure script modifies system configuration files,
# and it can get annoying if it runs twice.
if [ ! -e $SITC_ROOT/ran_configure ] && [ "$UPGRADE_WEBMO" != "true" ]; then
	echo "Configuring httpd..."
	# Configure httpd
	$SITC_ROOT/scripts/centos/configure
	touch $SITC_ROOT/ran_configure
fi

$SITC_ROOT/scripts/common/install_webmo
