#!/bin/bash

SITC_ROOT=$1

echo "Installing csh..."
# Install csh
sudo yum -y install csh >> $SITC_ROOT/sitc.log 2>&1

echo "Installing gcc-gfortran..."
# Install gcc-gfortran
sudo yum -y install gcc-gfortran >> $SITC_ROOT/sitc.log 2>&1

$SITC_ROOT/scripts/common/install_gamess $SITC_ROOT
