#!/bin/bash

# Run script to update os
$SITC_ROOT/scripts/centos/os_update

echo "Installing mlocate..."
# Install mlocate
sudo yum -y install mlocate >> $SITC_ROOT/sitc.log 2>&1
sudo updatedb

echo "Installing nano..."
# Install nano
sudo yum -y install nano >> $SITC_ROOT/sitc.log 2>&1

echo "Installing patch..."
# Install patch
sudo yum -y install patch >> $SITC_ROOT/sitc.log 2>&1
