#!/bin/bash

#Obtain current directory
SITC_ROOT=$1

version=`cat /etc/redhat-release | grep -o '[0-9]' | awk '{ print $1 }' | head -n 1`

#Run script to update os
$SITC_ROOT/scripts/centos/os_update $SITC_ROOT

echo "Installing httpd..."
# Install httpd
sudo yum -y install httpd >> $SITC_ROOT/sitc.log 2>&1
if (( "$version" == 6 )); then
	sudo chkconfig --add httpd >> $SITC_ROOT/sitc.log 2>&1
	sudo service httpd start >> $SITC_ROOT/sitc.log 2>&1
else
	sudo systemctl enable httpd >> $SITC_ROOT/sitc.log 2>&1
	sudo systemctl start httpd >> $SITC_ROOT/sitc.log 2>&1
fi

echo "Installing perl..."
# Install perl
sudo yum -y install perl >> $SITC_ROOT/sitc.log 2>&1
sudo yum -y install perl-CGI >> $SITC_ROOT/sitc.log 2>&1

echo "Installing mlocate..."
# Install mlocate
sudo yum -y install mlocate >> $SITC_ROOT/sitc.log 2>&1
sudo updatedb

echo "Installing nano..."
# Install nano
sudo yum -y install nano >> $SITC_ROOT/sitc.log 2>&1

echo "Installing patch..."
# Install patch
sudo yum -y install patch >> $SITC_ROOT/sitc.log 2>&1
