#!/bin/bash

echo "Updating operating system..."
# Update operating system
sudo yum clean all >> $SITC_ROOT/sitc.log 2>&1
yum makecache fast >> $SITC_ROOT/sitc.log 2>&1
sudo yum -y update >> $SITC_ROOT/sitc.log 2>&1
