#!/bin/bash

sudo yum -y install openssl mod_ssl &> /dev/null
IP=`curl -s "http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip" -H "X-Google-Metadata-Request: True"`
keyname="localhost"
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/pki/tls/private/$keyname.key -out /etc/pki/tls/certs/$keyname.crt -subj "/CN=$IP" &> /dev/null
sudo systemctl restart httpd
