#!/bin/bash

echo "Installing apache..."
# Install apache
sudo apt-get -y install apache2 >> $SITC_LOG 2>&1

echo "Installing suexec..."
# Install suexec. Using custom rather than pristine because debian 7 doesn't have it in the repositories.
sudo apt-get -y install apache2-suexec-custom >> $SITC_LOG 2>&1

echo "Installing perl..."
# Install perl
sudo apt-get -y install libcgi-pm-perl >> $SITC_LOG 2>&1

echo "Configuring apache..."
# Configure apache
$SITC_ROOT/scripts/debian/configure

$SITC_ROOT/scripts/common/install_webmo
