#!/bin/bash

echo "Installing gfortran..."
# Install gfortran
sudo apt-get -y install gfortran >> $SITC_LOG 2>&1

echo "Installing make..."
# Install make
sudo apt-get -y install make >> $SITC_LOG 2>&1

echo "Installing patch..."
# Install patch
sudo apt-get -y install patch >> $SITC_LOG 2>&1
