#!/bin/bash

echo "Installing gfortran..."
# Install gfortran
sudo apt-get -y install gfortran >> $SITC_ROOT/sitc.log 2>&1

echo "Installing make..."
# Install make
sudo apt-get -y install make >> $SITC_ROOT/sitc.log 2>&1

$SITC_ROOT/scripts/common/install_espresso
