#!/bin/bash

#Obtain current directory
SITC_ROOT=$1

#update os
$SITC_ROOT/scripts/debian/os_update $SITC_ROOT

echo "Installing apache..."
# Install apache
sudo apt-get -y install apache2 >> $SITC_ROOT/sitc.log 2>&1

echo "Installing suexec..."
# Install suexec. Using custom rather than pristine because debian 7 doesn't have it in the repositories.
sudo apt-get -y install apache2-suexec-custom >> $SITC_ROOT/sitc.log 2>&1

echo "Installing perl..."
# Install perl
sudo apt-get -y install libcgi-pm-perl >> $SITC_ROOT/sitc.log 2>&1

echo "Installing mlocate..."
# Install mlocate
sudo apt-get -y install mlocate >> $SITC_ROOT/sitc.log 2>&1
sudo updatedb

echo "Installing patch..."
# Install patch
sudo apt-get -y install patch >> $SITC_ROOT/sitc.log 2>&1

echo "Installing vim..."
# Install vim. It is far superior to vi.
sudo apt-get -y install vim >> $SITC_ROOT/sitc.log 2>&1
