#!/bin/bash

#Obtain current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#update os
$DIR/os_update

echo "Installing apache..."
# Install apache
sudo apt-get -y install apache2 >> $DIR/../../sitc.log 2>&1

echo "Installing suexec..."
# Install suexec. Using custom rather than pristine because debian 7 doesn't have it in the repositories.
sudo apt-get -y install apache2-suexec-custom >> $DIR/../../sitc.log 2>&1

echo "Installing perl..."
# Install perl
sudo apt-get -y install libcgi-pm-perl >> $DIR/../../sitc.log 2>&1

echo "Installing mlocate..."
# Install mlocate
sudo apt-get -y install mlocate >> $DIR/../../sitc.log 2>&1
sudo updatedb

echo "Installing patch..."
# Install patch
sudo apt-get -y install patch >> $DIR/../../sitc.log 2>&1

echo "Installing vim..."
# Install vim. It is far superior to vi.
sudo apt-get -y install vim >> $DIR/../../sitc.log 2>&1
