#!/bin/bash

# update os
$SITC_ROOT/scripts/debian/os_update $SITC_ROOT

echo "Installing mlocate..."
# Install mlocate
sudo apt-get -y install mlocate >> $SITC_LOG 2>&1
sudo updatedb

echo "Installing patch..."
# Install patch
sudo apt-get -y install patch >> $SITC_LOG 2>&1

echo "Installing vim..."
# Install vim. It is far superior to vi.
sudo apt-get -y install vim >> $SITC_LOG 2>&1
