#!/bin/bash

#Obtain current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Updating operating system..."
# Update operating system
sudo apt-get -y update >> $DIR/../../sitc.log 2>&1
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade >> $DIR/../../sitc.log 2>&1
