#!/bin/bash

IP=`curl -s "http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip" -H "X-Google-Metadata-Request: True"`
DN=$IP.xip.io

sudo apt-get -y install python-certbot-apache -t jessie-backports
sudo certbot certonly --webroot --webroot-path=/var/www/html -d $DN

sudo sed -i.orig "s&SSLCertificateFile.*&SSLCertificateFile /etc/letsencrypt/live/$DN/cert.pem&g" /etc/apache2/sites-available/default-ssl.conf
sudo sed -i "s&SSLCertificateKeyFile.*&SSLCertificateKeyFile /etc/letsencrypt/live/$DN/privkey.pem&g" /etc/apache2/sites-available/default-ssl.conf
sudo sed -i "s&#SSLCertificateChainFile.*&SSLCertificateChainFile /etc/letsencrypt/live/$DN/chain.pem&g" /etc/apache2/sites-available/default-ssl.conf

echo "
<VirtualHost *:80>
        Redirect permanent / https://$DN/
</VirtualHost>" | sudo tee --append /etc/apache2/apache2.conf > /dev/null

sudo systemctl restart apache2

