#!/bin/bash

#Obtain current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ `whoami` != "webmo" ]; then
	echo "Please run this script as the webmo user"
	exit
fi


image="debian-8"
name="supernode"
project="sitc-1070"
zone="us-central1-f"
disksize="10"
#memory can by any of standard, highmem, highcpu
memory="standard"
#numcpus can be any of 1, 2, 4, 8, 16, 32
numcpus="1"

if [ ! -e /home/webmo/.ssh/id_rsa ]; then
	echo
	echo "####### WHEN PROMPTED: leave your public/private rsa key pair passphrase-less #######"
	echo
	ssh-keygen
fi

gcloud compute --project "$project" instances create "$name" --zone "$zone" --machine-type "n1-$memory-$numcpus" --network "default" --maintenance-policy "MIGRATE" --scopes "https://www.googleapis.com/auth/cloud.useraccounts.readonly","https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring.write" --image "$image" --boot-disk-size "$disksize" --boot-disk-type "pd-standard" --boot-disk-device-name "$name"

ip=`gcloud compute instances list "$name" | tail -1 | rev | cut -d " " -f 2 | rev`

echo "curl -O http://107.4.53.178/~nathan/sitc.tar.gz && tar xzf sitc.tar.gz && ./sitc/compute_install" | gcloud compute ssh $name --zone $zone

echo "
Ensure that you're logged in as the webmo user and setup passwordless logins by executing (use "webmo" as the password when prompted):
 ssh-copy-id webmo@$ip

Then, test that this works by executing the following (it should connect without prompting for a password):
 ssh webmo@$ip

Change the password for webmo to something more secure than "webmo":
 passwd webmo

In the WebMO admin page, under Remote Server Manager, add $name as a remote server with:
 Server name:		$name
 Hostname:		$ip
 CPU cores:		$numcpus
 Username:		webmo
 Home directory:	/home/webmo
 Scratch directory:	/tmp
 Protocal:		ssh

Finally, under Interface Manager, select $name as the server being edited and enable Mopac. Verify that the paths for the interface were set up correctly.
"
