#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# On CentOS, gcloud is in /usr/local/bin and we can't find it.
export PATH=/usr/local/bin/:$PATH

source $DIR/api.conf

if [ `whoami` != "$WEBMO_USER" ]; then
        echo "Please run this script as the webmo user"
        exit
fi

zone=`gcloud compute instances list | grep "$(hostname)" | awk '{print $2}'`

gcloud config set compute/zone $zone

cmd=$1
name=$2
if [ -z "$name" ]; then
	name=$NAME_BASE
fi
$DIR/scripts/$cmd $name
