#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ `whoami` != "$WEBMO_USER" ]; then
        echo "Please run this script as the webmo user"
        exit
fi

zone=`gcloud compute instances list | grep "$(hostname)" | awk '{print $2}'`

gcloud config set compute/zone $zone
