#!/bin/bash

echo "Creating a compute node..."

name="$1"
#Obtain list of available images through $ gcloud compute images list
image="debian-8"
disksize="10"
#memory can by any of standard, highmem, highcpu
memory="standard"
#numcpus can be any of 1, 2, 4, 8, 16, 32
numcpus="1"

gcloud compute instances create "$name" --machine-type "n1-$memory-$numcpus" --image "$image" --boot-disk-size "$disksize"

ip=`gcloud compute instances list "$name" | tail -1 | rev | cut -d " " -f 2 | rev`

if [ ! -e "/home/$USER/.ssh/google_compute_engine" ]; then
	echo "/home/$USER/.ssh/google_compute_engine" | ssh-keygen -N ""
fi
gcloud compute config-ssh
rm /home/$USER/.ssh/config

#Automatic passwordless ssh
cp /home/$USER/.ssh/google_compute_engine /home/$USER/.ssh/id_rsa
#Remove our ip from knownhosts
ssh-keygen -R $ip

echo
echo "########## SSHing into $USER@$name ##########"

ssh -o StrictHostKeyChecking=no $name

echo "########## Finished work in $USER@$name ##########"
echo

echo "In the WebMO admin page, under Remote Server Manager, add $name as a remote server with:
 Server name:		$name
 Hostname:		$name
 CPU cores:		$numcpus
 Username:		$USER
 Home directory:	/home/$USER
 Scratch directory:	/tmp
 Protocal:		ssh

Under Interface Manager, select $name as the server being edited and enable Mopac. Verify that the paths for the interface were set up correctly.
"
