#!/bin/bash

echo "Creating a compute node..."

name="$1"

gcloud compute instances create "$name" --machine-type "n1-$MEMORY-$NUMCPUS" --image-family "$IMAGE_FAMILY" --image-project "$IMAGE_PROJECT" --boot-disk-size "$DISKSIZE"

# Set up ssh keys
if [ ! -e "/home/$WEBMO_USER/.ssh/google_compute_engine" ]; then
	echo "/home/$WEBMO_USER/.ssh/google_compute_engine" | ssh-keygen -N ""
fi
gcloud compute config-ssh
rm /home/$WEBMO_USER/.ssh/config
# Automatic passwordless ssh
cp /home/$WEBMO_USER/.ssh/google_compute_engine /home/$WEBMO_USER/.ssh/id_rsa
# Remove the ip from knownhosts in case it collides with an existing one
ip=`gcloud compute instances list "$name" | tail -1 | rev | awk '{ print $2 }' | rev`
ssh-keygen -R $ip

echo
echo "########## Configuring $WEBMO_USER@$name ##########"

for engine in `sed 's/,/ /g' <<< $ENGINES`; do
	varname=${engine^^}_TAR
	if [ -n "${!varname}" ]; then
		echo "Copying ${!varname} to $WEBMO_USER@$name"
		scp ${!varname} $WEBMO_USER@${name}:/${!varname}
	fi
done

if [ -z "$REMOTE_SERVER_ENGINES" ]; then
	REMOTE_SERVER_ENGINES="$ENGINES"
fi

scp $SITC_ROOT/sitc.tar.gz $WEBMO_USER@${name}:/$SITC_ROT/sitc.tar.gz

echo "tar xzf $SITC_ROOT/sitc.tar.gz && $SITC_ROOT/sitc/install -y --SKIP_WEBMO=true --REMOTE_SERVER=false --ENGINES=$REMOTE_SERVER_ENGINES" | ssh -o StrictHostKeyChecking=no $name

echo "########## Finished work in $WEBMO_USER@$name ##########"
echo

echo "In the WebMO admin page, under Remote Server Manager, add $name as a remote server with:
 Server name:           $name
 Hostname:              $name
 CPU cores:             $NUMCPUS
 Username:              $WEBMO_USER
 Home directory:        /home/$WEBMO_USER
 Scratch directory:     /tmp
 Protocal:              ssh

Under Interface Manager, select $name as the server being edited and enable Mopac. Verify that the paths for the interface were set up correctly.
"
